function proportionComparisonChosen = importfileForFigure12(filename, dataLines)
%IMPORTFILE Import data from a text file
%  PROPORTIONCOMPARISONCHOSEN = IMPORTFILE(FILENAME) reads data from
%  text file FILENAME for the default selection.  Returns the data as a
%  table.
%
%  PROPORTIONCOMPARISONCHOSEN = IMPORTFILE(FILE, DATALINES) reads data
%  for the specified row interval(s) of text file FILENAME. Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  proportionComparisonChosen = importfile("/ObserverData/Experiment8/proportionComparisonChosen.csv", [3, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 30-Apr-2023 15:14:10

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [3, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 127, "Encoding", "UTF-8");

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Subject", "CN_AT_0003", "CN_AT_1", "CN_AT_2", "CN_AT_3", "CN_AT_4", "CN_AT_5", "CN_AT_6", "CN_AT_7", "CN_AT_8", "CN_AT_9", "CN_AT_10", "CN_AT_11", "CN_AT_12", "CN_AT_13", "CN_AT_14", "CN_AT_15", "CN_AT_16", "CN_AT_17", "CN_AT_18", "CN_AT_19", "CN_AT_20", "CN_AT_bagel", "CN_AT_bagel1", "CN_AT_bagel2", "CN_AT_bagel3", "CN_AT_bagel4", "CN_AT_bagel5", "CN_AT_bagel6", "CN_AT_bagel7", "CN_AT_bagel8", "CN_AT_bagel9", "CN_AT_bagel10", "CN_AT_bagel11", "CN_AT_bagel12", "CN_AT_bagel13", "CN_AT_bagel14", "CN_AT_bagel15", "CN_AT_bagel16", "CN_AT_bagel17", "CN_AT_bagel18", "CN_AT_bagel19", "CN_AT_bagel20", "CN_AT_fun", "CN_AT_fun1", "CN_AT_fun2", "CN_AT_fun3", "CN_AT_fun4", "CN_AT_fun5", "CN_AT_fun6", "CN_AT_fun7", "CN_AT_fun8", "CN_AT_fun9", "CN_AT_fun10", "CN_AT_fun11", "CN_AT_fun12", "CN_AT_fun13", "CN_AT_fun14", "CN_AT_fun15", "CN_AT_fun16", "CN_AT_fun17", "CN_AT_fun18", "CN_AT_fun19", "CN_AT_fun20", "CN_AT_oven", "CN_AT_oven1", "CN_AT_oven2", "CN_AT_oven3", "CN_AT_oven4", "CN_AT_oven5", "CN_AT_oven6", "CN_AT_oven7", "CN_AT_oven8", "CN_AT_oven9", "CN_AT_oven10", "CN_AT_oven11", "CN_AT_oven12", "CN_AT_oven13", "CN_AT_oven14", "CN_AT_oven15", "CN_AT_oven16", "CN_AT_oven17", "CN_AT_oven18", "CN_AT_oven19", "CN_AT_oven20", "CN_AT_manos", "CN_AT_manos1", "CN_AT_manos2", "CN_AT_manos3", "CN_AT_manos4", "CN_AT_manos5", "CN_AT_manos6", "CN_AT_manos7", "CN_AT_manos8", "CN_AT_manos9", "CN_AT_manos10", "CN_AT_manos11", "CN_AT_manos12", "CN_AT_manos13", "CN_AT_manos14", "CN_AT_manos15", "CN_AT_manos16", "CN_AT_manos17", "CN_AT_manos18", "CN_AT_manos19", "CN_AT_manos20", "CN_AT_revival", "CN_AT_revival1", "CN_AT_revival2", "CN_AT_revival3", "CN_AT_revival4", "CN_AT_revival5", "CN_AT_revival6", "CN_AT_revival7", "CN_AT_revival8", "CN_AT_revival9", "CN_AT_revival10", "CN_AT_revival11", "CN_AT_revival12", "CN_AT_revival13", "CN_AT_revival14", "CN_AT_revival15", "CN_AT_revival16", "CN_AT_revival17", "CN_AT_revival18", "CN_AT_revival19", "CN_AT_revival20"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
proportionComparisonChosen = readtable(filename, opts);

end