function subjectThreshold = importfileForFigure7(filename, dataLines)
%IMPORTFILE Import data from a text file
%  SUBJECTTHRESHOLD = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  SUBJECTTHRESHOLD = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  subjectThreshold = importfile("/ObserverData/Experiment6/subjectThreshold.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 27-Apr-2023 16:44:29

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 19, "Encoding", "UTF-8");

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Subject", "CN_AT_0003", "CN_AT_1", "CN_AT_2", "CN_AT_bagel", "CN_AT_bagel1", "CN_AT_bagel2", "CN_AT_committee", "CN_AT_committee1", "CN_AT_committee2", "CN_AT_content", "CN_AT_content1", "CN_AT_content2", "CN_AT_observer", "CN_AT_observer1", "CN_AT_observer2", "CN_AT_revival", "CN_AT_revival1", "CN_AT_revival2"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "Subject", "TrimNonNumeric", true);
opts = setvaropts(opts, "Subject", "ThousandsSeparator", ",");

% Import the data
subjectThreshold = readtable(filename, opts);

end